
%% set the data want to analyse
onWorkstation = 0;
sheetFolder = '###\20230208 SLB\processed data RoSEO\RoSEO_dataSheet\';
sheetName = {'20230208_RoIsheet_data26_31_FoV1_demo.xlsx'
    %'20230208_RoIsheet_data15_19_FoV1.xlsx',...
    %'20230208_RoIsheet_data20_25_FoV1.xlsx',...
    %'20230208_RoIsheet_data15_19_FoV2.xlsx',...
    %'20230208_RoIsheet_data20_25_FoV2.xlsx',...
    %'20230208_RoIsheet_data26_31_FoV2.xlsx',...
    %'20230208_RoIsheet_data26_31_FoV1.xlsx'
};

%%
for ii = 1:numel(sheetName)
%% read the sheet info and create necessary folder
opts = detectImportOptions([sheetFolder,sheetName{ii}]);
opts = setvartype(opts,'char');  % or 'string'
sheet_cur= readtable([sheetFolder,sheetName{ii}],opts);
if onWorkstation == 0
sheet_cur = string(table2array(sheet_cur(:,2:3)));
else 
sheet_cur = string(table2array(sheet_cur(:,[2,4])));
end
para_data = f_table2struct(sheet_cur);

%

% check if the save fileExit, create new one
time = datestr(now,'yyyymmdd_HH_MM');
if isfolder(strcat(para_data.saveData_folderName))==0
    mkdir(strcat(para_data.saveData_folderName));
end

if isfolder(strcat(para_data.SMLM_image_save_folder))==0
    mkdir(strcat(para_data.SMLM_image_save_folder));
end



if sheet_cur(sheet_cur(:,1)=='inter_results_save_folder',2)==""
    inter_results_save_folder = strcat(para_data.saveData_folderName,string(time),'results_save');
    mkdir(inter_results_save_folder);
else
   inter_results_save_folder = sheet_cur(sheet_cur(:,1)=='inter_results_save_folder',2);
end
save(strcat(inter_results_save_folder,'/sheet_cur.mat'),'para_data','sheet_cur');
%% create tform using the imaging sample
if sheet_cur(sheet_cur(:,1)=='do_tform',2)=="1"
pixel_sz = 1; % thurderstorm camera pixel size setting
photonThred = 100;
frame_thred = 20000;
ratio_y2x = 1.14;
filter_close_emitter = 0;
xy_ch_list_together = 1;                                                                                                                                                                                                                                                                                                                                                                                                 

f_tform_use_sample(para_data.locSheetFolder_for_tfrom,...
    para_data.frame_width,...
    pixel_sz,...
    photonThred,...
    frame_thred,...
    ratio_y2x,...
    para_data.tform_ROI_center,...
    para_data.tform_ROI_size_each,...
    para_data.tform_ROI_size_whole,...
    para_data.tform_data,...
    para_data.tform_N_Fov,...
    filter_close_emitter,...
    inter_results_save_folder, ...
    xy_ch_list_together,...
    para_data.SMLM_image_save_folder,...
    para_data.locSheetFolder_for_tfrom_beads,...
    para_data.tform_data_beads,...
    para_data.tform_data_pre_name);
end
%% crop image using the above tform
if sheet_cur(sheet_cur(:,1)=='do_crop',2)=="1"
f_crop_image_usig_whole_pixels(...
    para_data.crop_data,...
    para_data.DatafileFolder,...
    inter_results_save_folder,...
    para_data.SMLM_image_save_folder,...
    para_data.crop_ROI_center,...
    para_data.frame_width,...
    para_data.crop_N_frame,...
    para_data.crop_ROI_all,...
    para_data.crop_N_FoV,...
    para_data.crop_ROI_each,...
    para_data.tform_ROI_size_each, ...
    para_data.crop_data_pre_name);
end
%% crop offset image
if sheet_cur(sheet_cur(:,1)=='do_crop',2)=="1"
f_crop_offset_using_whole_pixels(...
    para_data.offSetName,...
    inter_results_save_folder,...
    para_data.SMLM_image_save_folder,...
    para_data.crop_ROI_center,...
    para_data.frame_width,...
    para_data.crop_ROI_all,...
    para_data.crop_N_FoV,...
    para_data.crop_ROI_each,...
    para_data.tform_ROI_size_each);

end
%% estimate background
if sheet_cur(sheet_cur(:,1)=='do_backgroundEst',2)=="1"
PSF_sz_half = 7;
gaussian_fit_size = 5;
pixel_sz = 1;
xy_ch_list_together = 1;
intensity_thred = 0;

f_background_estimation_by_subtrubct_SMs_small_FoV(...
    para_data.locSheetFolder_for_tfrom,...
    xy_ch_list_together,...
    pixel_sz,...
    para_data.crop_data,...
    para_data.SMLM_image_save_folder,...
    inter_results_save_folder,...
    para_data.crop_ROI_center,...
    para_data.frame_width,...
    para_data.crop_N_frame,...
    para_data.crop_ROI_all,...
    para_data.crop_N_FoV,...
    para_data.crop_ROI_each,...
    para_data.tform_ROI_size_each,...
    gaussian_fit_size,...
    PSF_sz_half,...
    intensity_thred, ...
    para_data.crop_data_pre_name)

end

close all;
%% estimate using RoSEO3D

addpath(genpath('F:\OneDrive - Washington University in St. Louis\github\RoSEO3D_in_use\'));
RoSEOPara = f_table2struct_RoSEOPara_3D(sheet_cur);

if sheet_cur(sheet_cur(:,1)=='do_RoSEO',2)=="1"

if isfolder(strcat(RoSEOPara.estResults_save_folder))==0
    mkdir(strcat(RoSEOPara.estResults_save_folder));
end
thred = 30;

f_RoSEO3D_input(...
    RoSEOPara,...
    para_data.SMLM_image_save_folder,...
    inter_results_save_folder,...
    RoSEOPara.dataID_analysed,...
    RoSEOPara.Nframe_analysed,...
    para_data.crop_ROI_each,...
    RoSEOPara.FoV_analysed,...
    para_data.crop_ROI_center,...
    RoSEOPara.estResults_save_folder,...
    thred)

end


%%

close all;
end

