%%
dens = 0.1;
figure();
subplot(1,3,1); 
scatter(thetaD(indx),z_cord(indx),8,omega(indx),'filled','MarkerFaceAlpha',dens,'MarkerEdgeAlpha',dens); ylabel('z(nm)'); xlabel('\theta(\circ)');
%hold on; scatter(thetaD1(indx),z(indx),2,'filled','k','MarkerFaceAlpha',.2,'MarkerEdgeAlpha',.2); ylabel('z(nm)'); xlabel('theta(\circ)');
ax = gca;
ax.FontSize = 10;  box on;
subplot(1,3,2);
scatter(phiD_cord(indx),x_cord(indx),8,omega(indx),'filled','MarkerFaceAlpha',dens,'MarkerEdgeAlpha',dens); ylabel('x(nm)'); xlabel('\phi(\circ)');
%hold on; scatter(phiD1(indx),x(indx),2,'filled','k','MarkerFaceAlpha',.2,'MarkerEdgeAlpha',.2); 
ax = gca;
ax.FontSize = 10;  box on;
subplot(1,3,3); 
scatter(phiD_cord(indx),y_cord(indx),8,omega(indx),'filled','MarkerFaceAlpha',dens,'MarkerEdgeAlpha',dens); ylabel('y(nm)'); xlabel('\phi(\circ)');
%hold on; scatter(phiD1(indx),y(indx),2,'filled','k','MarkerFaceAlpha',.2,'MarkerEdgeAlpha',.2); 
ax = gca;
ax.FontSize = 10; box on;
whitebg('w');
set(gcf,'Color','w');

figure();
subplot(1,3,1); 
scatter(thetaD(indx),z_cord(indx),8,omega(indx),'filled','MarkerFaceAlpha',dens,'MarkerEdgeAlpha',dens); ylabel('z(nm)'); xlabel('\theta(\circ)');
hold on; scatter(thetaD1(indx),z_cord(indx),2,'filled','r','MarkerFaceAlpha',.2,'MarkerEdgeAlpha',.2); ylabel('z(nm)'); xlabel('\theta(\circ)');
ax = gca;
ax.FontSize = 10;  box on;
subplot(1,3,2); 
scatter(phiD_cord(indx),x_cord(indx),8,omega(indx),'filled','MarkerFaceAlpha',dens,'MarkerEdgeAlpha',dens); ylabel('x(nm)'); xlabel('\phi(\circ)');
hold on; scatter(phiD1(indx),x_cord(indx),2,'filled','r','MarkerFaceAlpha',.2,'MarkerEdgeAlpha',.2); 
ax = gca;
ax.FontSize = 10; box on;
subplot(1,3,3); 
scatter(phiD_cord(indx),y_cord(indx),8,omega(indx),'filled','MarkerFaceAlpha',dens,'MarkerEdgeAlpha',dens); ylabel('y(nm)'); xlabel('\phi(\circ)');
hold on; scatter(phiD1(indx),y_cord(indx),2,'filled','r','MarkerFaceAlpha',.2,'MarkerEdgeAlpha',.2); 
ax = gca; 
ax.FontSize = 10; 
box on;
set(gcf,'Color','w');